export const Bladers = {
    getBladers() {
        return [
            {
                "id": "259854970",
                "name": "JARED",
                "swissWins": 7,
                "top16": true,
                "winnersWins": 1,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 85,
                "rank": -1
            },
            {
                "id": "262701009",
                "name": "BRYXX",
                "swissWins": 1,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 15,
                "rank": -1
            },
            {
                "id": "262700982",
                "name": "KYOYA",
                "swissWins": 2,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 20,
                "rank": -1
            },
            {
                "id": "259854987",
                "name": "ITAMI",
                "swissWins": 2,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 30,
                "rank": -1
            },
            {
                "id": "259854983",
                "name": "YOMI",
                "swissWins": 5,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 55,
                "rank": -1
            },
            {
                "id": "262701018",
                "name": "REI",
                "swissWins": 3,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 25,
                "rank": -1
            },
            {
                "id": "259854982",
                "name": "CASTER",
                "swissWins": 7,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 115,
                "rank": -1,
                "desc":"An enthusiast since plastic gen, Caster is no stranger to blading. The allure of Beyblade has brought this fighter back looking for a challenge. Armed with his trusty Samurai Saber 9-60 LR, he seeks the glory of X. He travels the land believing that the answer lies in the heart of battle.",
                "signature":"Samurai Saber 9-60 LR"
            },
            {
                "id": "259854992",
                "name": "ARVINE",
                "swissWins": 10,
                "top16": true,
                "winnersWins": 2,
                "losersWins": 2,
                "first": false,
                "second": false,
                "third": true,
                "points": 155,
                "rank": -1,
                "desc": "Heyo My name is Arvine ~ Beyblading is a completely different hobby for me and its been so fun! This is my first time on the podium. I got all my unrestricted blades from my closest people in the community! S/O JM - Trish - Trystan. A lot of people say Impact Drake is my ace bey, but its not aha. Its such a fun blade though! Impact Drake 360Point \u201cBasta Blader, Sweet Lover\u201d.",
                "signature": "Impact Drake 3-60 P"
            },
            {
                "id": "259855003",
                "name": "DAVE",
                "swissWins": 2,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 20,
                "rank": -1
            },
            {
                "id": "262700993",
                "name": "KIRYU",
                "swissWins": 4,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 30,
                "rank": -1
            },
            {
                "id": "261054016",
                "name": "RAY",
                "swissWins": 8,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 80,
                "rank": -1
            },
            {
                "id": "259854993",
                "name": "SCORPIO SPEAR RAY",
                "swissWins": 2,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 20,
                "rank": -1
            },
            {
                "id": "259855002",
                "name": "LANS",
                "swissWins": 8,
                "top16": true,
                "winnersWins": 0,
                "losersWins": 2,
                "first": false,
                "second": false,
                "third": false,
                "points": 90,
                "rank": -1
            },
            {
                "id": "259854981",
                "name": "JAREN JAMES",
                "blader_name": "TOP JAREN X",
                "swissWins": 9,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 3,
                "first": false,
                "second": false,
                "third": false,
                "points": 115,
                "rank": -1
            },
            {
                "id": "259854974",
                "name": "TRISH",
                "swissWins": 6,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 3,
                "first": false,
                "second": false,
                "third": false,
                "points": 75,
                "blader_name": "Brawnwen",
                "rank": -1
            },
            {
                "id": "259854969",
                "name": "WREKCY",
                "swissWins": 6,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 135,
                "rank": -1,
                "desc":"BladerWrekcy, long called the “Practice King,” defied all odds to take 2nd place. With Aero Pegasus’ speed, Scorpio Spear’s power, and Wizard Rod’s precision, he turned heads and silenced doubts. No longer just a sparring legend—BladerWrekcy has entered the real fight."
            },
            {
                "id": "259854977",
                "name": "ALLEN",
                "swissWins": 5,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 55,
                "rank": -1
            },
            {
                "id": "259854976",
                "name": "JINZOH",
                "swissWins": 3,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 25,
                "rank": -1
            },
            {
                "id": "259854991",
                "name": "KUBZ",
                "swissWins": 3,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 25,
                "rank": -1
            },
            {
                "id": "259854968",
                "name": "ANDREW",
                "swissWins": 1,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 15,
                "rank": -1
            },
            {
                "id": "259854984",
                "name": "JEKO",
                "swissWins": 4,
                "top16": true,
                "winnersWins": 0,
                "losersWins": 1,
                "first": false,
                "second": false,
                "third": false,
                "points": 45,
                "rank": -1
            },
            {
                "id": "259854978",
                "name": "JEFF",
                "blader_name": "SHIRO",
                "swissWins": 9,
                "top16": false,
                "winnersWins": 6,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 205,
                "rank": -1,
                "desc":"I am the Bone of my Rod, Steel is my Scorpio and Dragoon is my Blood. I have created over a Thousand Blades, Unaware of beginning, Nor aware of the end. Unlimited Blade Works. 1/3 of StartEnd -SHIRO(Jeff)",
                "signature":"Cobalt Dragoon 4-55 E"
            },
            {
                "id": "259854989",
                "name": "PATRICK G",
                "swissWins": 5,
                "top16": true,
                "winnersWins": 5,
                "losersWins": 0,
                "first": true,
                "second": false,
                "third": false,
                "points": 155,
                "rank": -1,
                "desc": "Patrick, a fierce Blader, unleashed his Golem Rock attack-type Beyblade with unmatched power, crushing opponents in every battle. Built for speed and impact, it was a true testament to his skill and strategy. With every spin, Patrick aimed for greatness, always striving to be the ultimate Blader."
            },
            {
                "id": "262700986",
                "name": "EVOLFLOW",
                "swissWins": 4,
                "top16": true,
                "winnersWins": 1,
                "losersWins": 1,
                "first": false,
                "second": false,
                "third": false,
                "points": 55,
                "rank": -1
            },
            {
                "id": "262701011",
                "name": "SHERWIN",
                "swissWins": 2,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 20,
                "rank": -1
            },
            {
                "id": "259854967",
                "name": "WITHAK",
                "swissWins": 9,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 110,
                "rank": -1
            },
            {
                "id": "259854973",
                "name": "ALFRED V",
                "blader_name": "ALFREDO",
                "swissWins": 4,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 65,
                "rank": -1
            },
            {
                "id": "259854996",
                "name": "MATT",
                "swissWins": 3,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 35,
                "rank": -1
            },
            {
                "id": "262701002",
                "name": "REGI",
                "swissWins": 0,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 10,
                "rank": -1
            },
            {
                "id": "262700984",
                "name": "MATEO",
                "swissWins": 3,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 25,
                "rank": -1
            },
            {
                "id": "259854972",
                "name": "MICHAEL",
                "blader_name": "ZEPH",
                "swissWins": 9,
                "top16": true,
                "winnersWins": 3,
                "losersWins": 1,
                "first": false,
                "second": true,
                "third": false,
                "points": 170,
                "rank": -1,
                "signature": "Cobalt Dragoon 1-60 L",
                "desc": "Representing Team Soju, Michael (\u201cZeph\u201d) built his name on Phoenix Wing 1-60 Rush, a reliable right-spin attacker known for its consistency in the stadium. For a while, he ran Cobalt Dragoon on Elevate, a strong meta combo, but the passive playstyle never suited him. He was just biding his time\u2014waiting for the left-spin winder to drop. Once it did, he switched to Cobalt Dragoon 1-60 Level, unlocking a fast, aggressive setup that matched his high-risk, high-reward playstyle."
            },
            {
                "id": "259854965",
                "name": "REN",
                "swissWins": 6,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 60,
                "rank": -1
            },
            {
                "id": "259854975",
                "name": "JAH",
                "swissWins": 4,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 40,
                "rank": -1
            },
            {
                "id": "259855001",
                "name": "IZSON",
                "swissWins": 4,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 50,
                "rank": -1
            },
            {
                "id": "259854997",
                "name": "DROAM",
                "swissWins": 11,
                "top16": true,
                "winnersWins": 1,
                "losersWins": 1,
                "first": false,
                "second": false,
                "third": false,
                "points": 145,
                "rank": -1,
                "desc": "I was once like any man\u2014living day to day, clocking in, clocking out, munching sinigang without a second thought. But then, something deep inside me snapped. I realized I wasn\u2019t just some guy... I had that fire in me. No\u2014not fire. I had that dog in me. No... that dragon. No...THAT BLADING GOD OF WAR.",
                "signature": "Cobalt Dragoon 5-60 R"
            },
            {
                "id": "259854964",
                "name": "PAU",
                "swissWins": 6,
                "top16": true,
                "winnersWins": 1,
                "losersWins": 3,
                "first": false,
                "second": false,
                "third": false,
                "points": 85,
                "rank": -1
            },
            {
                "id": "259854995",
                "name": "GABBY",
                "swissWins": 4,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 55,
                "rank": -1
            },
            {
                "id": "259854966",
                "name": "YEYOH",
                "swissWins": 6,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 70,
                "rank": -1
            },
            {
                "id": "259855004",
                "name": "BAILEYBOYS",
                "swissWins": 1,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 15,
                "rank": -1
            },
            {
                "id": "259854986",
                "name": "SIP",
                "swissWins": 5,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 45,
                "rank": -1
            },
            {
                "id": "261054013",
                "name": "ETHAN",
                "swissWins": 3,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 25,
                "rank": -1
            },
            {
                "id": "259854985",
                "name": "JETHRO",
                "swissWins": 2,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 30,
                "rank": -1
            },
            {
                "id": "259854971",
                "name": "RAUGGHI",
                "swissWins": 3,
                "top16": true,
                "winnersWins": 1,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 45,
                "rank": -1
            },
            {
                "id": "259854998",
                "name": "JEPOY",
                "swissWins": 4,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 30,
                "rank": -1
            },
            {
                "id": "259854988",
                "name": "SUNGANATOR",
                "swissWins": 5,
                "top16": true,
                "winnersWins": 2,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 75,
                "rank": -1
            },
            {
                "id": "259855000",
                "name": "JWRECK",
                "swissWins": 8,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 80,
                "rank": -1
            },
            {
                "id": "259854999",
                "name": "ADZILLA",
                "swissWins": 7,
                "top16": true,
                "winnersWins": 0,
                "losersWins": 1,
                "first": false,
                "second": false,
                "third": false,
                "points": 70,
                "rank": -1
            },
            {
                "id": "259854994",
                "name": "MR.PRESIDENT",
                "swissWins": 6,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 100,
                "rank": -1
            },
            {
                "id": "259854990",
                "name": "TAN2",
                "swissWins": 2,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 20,
                "rank": -1
            },
            {
                "id": "259854980",
                "name": "MIG",
                "swissWins": 7,
                "top16": true,
                "winnersWins": 0,
                "losersWins": 3,
                "first": false,
                "second": false,
                "third": false,
                "points": 165,
                "rank": -1,
                "signature": "Phoenix Wing 1-60 LR",
                "desc": "Born through the flames of perseverance and determination. Flying on the wings of freedom, soaring to new heights. With a balance of technical skill and raw power, Mig will fight tooth and nail to reach the top"
            },
            {
                "id": "259854979",
                "name": "STEVEN",
                "swissWins": 3,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 35,
                "rank": -1
            },
            {
                "id": "261054017",
                "name": "LEX",
                "swissWins": 5,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 45,
                "rank": -1
            },
            {
                "id": "261054004",
                "name": "CHRISTIAN C",
                "swissWins": 2,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 20,
                "rank": -1
            },
            {
                "id": "259855043",
                "name": "RICH",
                "swissWins": 0,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 10,
                "rank": -1
            },
            {
                "id": "261054018",
                "name": "RICK",
                "swissWins": 0,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 10,
                "rank": -1
            },
            {
                "id": "261054003",
                "name": "BLACS",
                "swissWins": 5,
                "top16": true,
                "winnersWins": 1,
                "losersWins": 2,
                "first": false,
                "second": false,
                "third": false,
                "points": 75,
                "rank": -1
            },
            {
                "id": "262700995",
                "name": "KAEL",
                "swissWins": 1,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 15,
                "rank": -1
            },
            {
                "id": "262700996",
                "name": "DANIEL",
                "swissWins": 3,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 25,
                "rank": -1
            },
            {
                "id": "262700997",
                "name": "JARED C",
                "swissWins": 4,
                "top16": true,
                "winnersWins": 0,
                "losersWins": 1,
                "first": false,
                "second": false,
                "third": false,
                "points": 45,
                "rank": -1
            },
            {
                "id": "262701017",
                "name": "VICKI",
                "swissWins": 2,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 20,
                "rank": -1
            },
            {
                "id": "261053997",
                "name": "RUBTAAH",
                "swissWins": 3,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 35,
                "rank": -1
            },
            {
                "id": "261054002",
                "name": "CHIEF",
                "swissWins": 1,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 15,
                "rank": -1
            },
            {
                "id": "261053996",
                "name": "CZ",
                "swissWins": 4,
                "top16": true,
                "winnersWins": 2,
                "losersWins": 1,
                "first": false,
                "second": false,
                "third": false,
                "points": 65,
                "rank": -1
            },
            {
                "id": "261054020",
                "name": "AARYA",
                "swissWins": 1,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 15,
                "rank": -1
            },
            {
                "id": "261054015",
                "name": "SETH",
                "swissWins": 4,
                "top16": true,
                "winnersWins": 2,
                "losersWins": 2,
                "first": false,
                "second": false,
                "third": true,
                "points": 90,
                "rank": -1
            },
            {
                "id": "261053987",
                "name": "JEREL",
                "swissWins": 3,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 25,
                "rank": -1
            },
            {
                "id": "261054019",
                "name": "JIYA",
                "swissWins": 0,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 10,
                "rank": -1
            },
            {
                "id": "261054006",
                "name": "CJ",
                "blader_name": "HellsSuboh",
                "swissWins": 7,
                "top16": true,
                "winnersWins": 5,
                "losersWins": 0,
                "first": true,
                "second": false,
                "third": false,
                "points": 185,
                "rank": -1,
                "signature": "Hells Hammer 7-60 LF",
                "desc": "CJ (\u201cHellsSuboh\u201d) made his post-exam return this season, and just like his previous win, his loyal 3 partner Beys never fail to Hammer out the competition! Beware of his secret Stance, put him in a tough spot and he may need to Rise from the Ashes to drag you into the depths of Hell!"
            },
            {
                "id": "261054007",
                "name": "STEPH",
                "swissWins": 2,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 20,
                "rank": -1
            },
            {
                "id": "261054014",
                "name": "JAKE",
                "swissWins": 4,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 30,
                "rank": -1
            },
            {
                "id": "261053998",
                "name": "JACOB",
                "swissWins": 1,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 15,
                "rank": -1
            },
            {
                "id": "261054008",
                "name": "RICHARD",
                "swissWins": 4,
                "top16": true,
                "winnersWins": 1,
                "losersWins": 1,
                "first": false,
                "second": false,
                "third": false,
                "points": 55,
                "rank": -1
            },
            {
                "id": "261053995",
                "name": "MIKO",
                "swissWins": 2,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 20,
                "rank": -1
            },
            {
                "id": "261053994",
                "name": "JP",
                "swissWins": 1,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 15,
                "rank": -1
            },
            {
                "id": "261054005",
                "name": "ALFRED S",
                "swissWins": 4,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 40,
                "rank": -1
            },
                {
                "id": "262701018",
                "name": "REI",
                "swissWins": 3,
                "top16": false,
                "winnersWins": 0,
                "losersWins": 0,
                "first": false,
                "second": false,
                "third": false,
                "points": 25,
                "rank": -1
            }
        ]
    }
}