export const Bladers = {
    getBladers() {
        return [
    {
        "id": "294066854",
        "clan_tag": "BNC",
        "name": "JUSTICE",
        "swissWins": 2,
        "swissLosses": 3,
        "topCut": false,
        "winnersWins": 0,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": false,
        "points": 30,
        "rank": -1
    },
    {
        "id": "294066848",
        "clan_tag": "BBCLB",
        "name": "BULLET BEY 1",
        "swissWins": 2,
        "swissLosses": 3,
        "topCut": false,
        "winnersWins": 0,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": false,
        "points": 30,
        "rank": -1
    },
    {
        "id": "294066841",
        "clan_tag": "T15",
        "name": "T15 2",
        "swissWins": 4,
        "swissLosses": 1,
        "topCut": true,
        "winnersWins": 0,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": false,
        "points": 60,
        "rank": -1
    },
    {
        "id": "294066852",
        "clan_tag": "SEND",
        "name": "STARTEND",
        "swissWins": 5,
        "swissLosses": 0,
        "topCut": false,
        "winnersWins": 0,
        "losersWins": 0,
        "swissChamp": true,
        "first": false,
        "second": false,
        "third": false,
        "points": 80,
        "rank": -1
    },
    {
        "id": "294066845",
        "clan_tag": "DYN",
        "name": "DYNASTY 1",
        "swissWins": 1,
        "swissLosses": 4,
        "topCut": false,
        "winnersWins": 0,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": false,
        "points": 20,
        "rank": -1
    },
    {
        "id": "294066847",
        "clan_tag": "UNDRTD",
        "name": "UNDRTD 2",
        "swissWins": 0,
        "swissLosses": 4,
        "topCut": false,
        "winnersWins": 0,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": false,
        "points": 10,
        "rank": -1
    },
    {
        "id": "294066846",
        "clan_tag": "UNDRTD",
        "name": "UNDRTD 1",
        "swissWins": 3,
        "swissLosses": 2,
        "topCut": true,
        "winnersWins": 1,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": false,
        "points": 60,
        "rank": -1
    },
    {
        "id": "294066853",
        "clan_tag": "BNC",
        "name": "FREEDOM",
        "swissWins": 1,
        "swissLosses": 3,
        "topCut": false,
        "winnersWins": 0,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": false,
        "points": 20,
        "rank": -1
    },
    {
        "id": "294066842",
        "clan_tag": "JARV",
        "name": "JARVEE 1",
        "swissWins": 0,
        "swissLosses": 4,
        "topCut": false,
        "winnersWins": 0,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": false,
        "points": 10,
        "rank": -1
    },
    {
        "id": "294066849",
        "clan_tag": "BBCLB",
        "name": "BULLET BEY 2",
        "swissWins": 2,
        "swissLosses": 3,
        "topCut": false,
        "winnersWins": 0,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": false,
        "points": 30,
        "rank": -1
    },
    {
        "id": "294066840",
        "clan_tag": "T15",
        "name": "T15 1",
        "swissWins": 3,
        "swissLosses": 2,
        "topCut": true,
        "winnersWins": 0,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": false,
        "points": 50,
        "rank": -1
    },
    {
        "id": "294066856",
        "clan_tag": "SOJU",
        "name": "SOJU",
        "swissWins": 3,
        "swissLosses": 2,
        "topCut": true,
        "winnersWins": 1,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": true,
        "points": 80,
        "rank": -1
    },
    {
        "id": "294066844",
        "clan_tag": "NV",
        "name": "NEW VESTROIA B2",
        "swissWins": 3,
        "swissLosses": 2,
        "topCut": false,
        "winnersWins": 0,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": false,
        "points": 40,
        "rank": -1
    },
    {
        "id": "294066851",
        "clan_tag": "DYN",
        "name": "DYNASTY",
        "swissWins": 3,
        "swissLosses": 2,
        "topCut": true,
        "winnersWins": 0,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": false,
        "points": 50,
        "rank": -1
    },
    {
        "id": "294066843",
        "clan_tag": "NV",
        "name": "NEW VESTROIA B1",
        "swissWins": 3,
        "swissLosses": 2,
        "topCut": true,
        "winnersWins": 2,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": true,
        "third": false,
        "points": 100,
        "rank": -1
    },
    {
        "id": "294066855",
        "clan_tag": "TRX",
        "name": "TRUE AXIS",
        "swissWins": 2,
        "swissLosses": 2,
        "topCut": false,
        "winnersWins": 0,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": false,
        "points": 30,
        "rank": -1
    },
    {
        "id": "294066850",
        "clan_tag": "KAOS",
        "name": "CHAOSBORN",
        "swissWins": 3,
        "swissLosses": 1,
        "topCut": true,
        "winnersWins": 3,
        "losersWins": 0,
        "swissChamp": false,
        "first": true,
        "second": false,
        "third": false,
        "points": 130,
        "rank": -1
    }
]
    }
}