export const Bladers = {
    getBladers() {
        return [
    {
        "id": "BNC",
        "clan_tag": "BNC",
        "name": "BEY N CHILL",
        "swissWins": 36,
        "swissLosses": 42,
        "topCut": true,
        "winnersWins": 2,
        "losersWins": 0,
        "swissChamp": true,
        "first": false,
        "second": false,
        "third": false,
        "points": 32,
        "rank": -1
    },
    {
        "id": "BBCLB",
        "clan_tag": "BBCLB",
        "name": "BULLET BEY CLUB",
        "swissWins": 8,
        "swissLosses": 12,
        "topCut": false,
        "winnersWins": 0,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": false,
        "points": 40,
        "rank": -1
    },
    {
        "id": "T15",
        "clan_tag": "T15",
        "name": "T15",
        "swissWins": 50,
        "swissLosses": 30,
        "topCut": true,
        "winnersWins": 10,
        "losersWins": 4,
        "swissChamp": true,
        "first": false,
        "second": false,
        "third": false,
        "points": 92,
        "rank": -1
    },
    {
        "id": "SEND",
        "clan_tag": "SEND",
        "name": "STARTEND",
        "swissWins": 38,
        "swissLosses": 8,
        "topCut": true,
        "winnersWins": 0,
        "losersWins": 2,
        "swissChamp": true,
        "first": false,
        "second": false,
        "third": false,
        "points": 72,
        "rank": -1
    },
    {
        "id": "DYN",
        "clan_tag": "DYN",
        "name": "DYNASTY",
        "swissWins": 22,
        "swissLosses": 32,
        "topCut": true,
        "winnersWins": 0,
        "losersWins": 10,
        "swissChamp": true,
        "first": false,
        "second": false,
        "third": true,
        "points": 57,
        "rank": -1
    },
    {
        "id": "UNDRTD",
        "clan_tag": "UNDRTD",
        "name": "UNDERRATED",
        "swissWins": 32,
        "swissLosses": 34,
        "topCut": true,
        "winnersWins": 12,
        "losersWins": 0,
        "swissChamp": true,
        "first": true,
        "second": false,
        "third": false,
        "points": 67,
        "rank": -1
    },
    {
        "id": "JARV",
        "clan_tag": "JARV",
        "name": "JARVEE",
        "swissWins": 28,
        "swissLosses": 38,
        "topCut": true,
        "winnersWins": 0,
        "losersWins": 2,
        "swissChamp": true,
        "first": false,
        "second": false,
        "third": false,
        "points": 2,
        "rank": -1
    },
    {
        "id": "SOJU",
        "clan_tag": "SOJU",
        "name": "SOJU",
        "swissWins": 12,
        "swissLosses": 10,
        "topCut": true,
        "winnersWins": 2,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": true,
        "points": 70,
        "rank": -1
    },
    {
        "id": "NV",
        "clan_tag": "NV",
        "name": "NEW VESTROIA",
        "swissWins": 34,
        "swissLosses": 32,
        "topCut": true,
        "winnersWins": 4,
        "losersWins": 6,
        "swissChamp": true,
        "first": false,
        "second": true,
        "third": false,
        "points": 122,
        "rank": -1
    },
    {
        "id": "TRX",
        "clan_tag": "TRX",
        "name": "TRUE AXIS",
        "swissWins": 16,
        "swissLosses": 16,
        "topCut": false,
        "winnersWins": 0,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": false,
        "points": 20,
        "rank": -1
    },
    {
        "id": "KAOS",
        "clan_tag": "KAOS",
        "name": "CHAOSBORN",
        "swissWins": 16,
        "swissLosses": 4,
        "topCut": true,
        "winnersWins": 6,
        "losersWins": 0,
        "swissChamp": true,
        "first": true,
        "second": false,
        "third": false,
        "points": 122,
        "rank": -1
    }
]
    }
}