export const Bladers = {
    getBladers() {
        return [
    {
        "id": "BNC",
        "clan_tag": "BNC",
        "name": "BEY N CHILL",
        "swissWins": 18,
        "swissLosses": 21,
        "topCut": true,
        "winnersWins": 1,
        "losersWins": 0,
        "swissChamp": true,
        "first": false,
        "second": false,
        "third": false,
        "points": 0,
        "rank": -1
    },
    {
        "id": "BBCLB",
        "clan_tag": "BBCLB",
        "name": "BULLET BEY CLUB",
        "swissWins": 4,
        "swissLosses": 6,
        "topCut": false,
        "winnersWins": 0,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": false,
        "points": 0,
        "rank": -1
    },
    {
        "id": "T15",
        "clan_tag": "T15",
        "name": "T15",
        "swissWins": 25,
        "swissLosses": 15,
        "topCut": true,
        "winnersWins": 5,
        "losersWins": 2,
        "swissChamp": true,
        "first": false,
        "second": false,
        "third": false,
        "points": 0,
        "rank": -1
    },
    {
        "id": "SEND",
        "clan_tag": "SEND",
        "name": "STARTEND",
        "swissWins": 19,
        "swissLosses": 4,
        "topCut": true,
        "winnersWins": 0,
        "losersWins": 1,
        "swissChamp": true,
        "first": false,
        "second": false,
        "third": false,
        "points": 0,
        "rank": -1
    },
    {
        "id": "DYN",
        "clan_tag": "DYN",
        "name": "DYNASTY",
        "swissWins": 11,
        "swissLosses": 16,
        "topCut": true,
        "winnersWins": 0,
        "losersWins": 5,
        "swissChamp": true,
        "first": false,
        "second": false,
        "third": true,
        "points": 0,
        "rank": -1
    },
    {
        "id": "UNDRTD",
        "clan_tag": "UNDRTD",
        "name": "UNDERRATED",
        "swissWins": 16,
        "swissLosses": 17,
        "topCut": true,
        "winnersWins": 6,
        "losersWins": 0,
        "swissChamp": true,
        "first": true,
        "second": false,
        "third": false,
        "points": 0,
        "rank": -1
    },
    {
        "id": "JARV",
        "clan_tag": "JARV",
        "name": "JARVEE",
        "swissWins": 14,
        "swissLosses": 19,
        "topCut": true,
        "winnersWins": 0,
        "losersWins": 1,
        "swissChamp": true,
        "first": false,
        "second": false,
        "third": false,
        "points": 0,
        "rank": -1
    },
    {
        "id": "SOJU",
        "clan_tag": "SOJU",
        "name": "SOJU",
        "swissWins": 6,
        "swissLosses": 5,
        "topCut": true,
        "winnersWins": 1,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": true,
        "points": 0,
        "rank": -1
    },
    {
        "id": "NV",
        "clan_tag": "NV",
        "name": "NEW VESTROIA",
        "swissWins": 17,
        "swissLosses": 16,
        "topCut": true,
        "winnersWins": 2,
        "losersWins": 3,
        "swissChamp": true,
        "first": false,
        "second": true,
        "third": false,
        "points": 0,
        "rank": -1
    },
    {
        "id": "TRX",
        "clan_tag": "TRX",
        "name": "TRUE AXIS",
        "swissWins": 8,
        "swissLosses": 8,
        "topCut": false,
        "winnersWins": 0,
        "losersWins": 0,
        "swissChamp": false,
        "first": false,
        "second": false,
        "third": false,
        "points": 0,
        "rank": -1
    },
    {
        "id": "KAOS",
        "clan_tag": "KAOS",
        "name": "CHAOSBORN",
        "swissWins": 8,
        "swissLosses": 2,
        "topCut": true,
        "winnersWins": 3,
        "losersWins": 0,
        "swissChamp": true,
        "first": true,
        "second": false,
        "third": false,
        "points": 0,
        "rank": -1
    }
]
    }
}